[project]
name = "antigravity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asgiref==3.11.1",
    "django==5.2.11",
    "django-extensions==4.1",
    "pip==25.2",
    "sqlparse==0.5.5",
]
